[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["./src/openapi.yaml", "./src/controllers/*"]

[[redirects]]
  from = "/api/v1/:splat"
  to = "/.netlify/functions/main/"
  status = 200
  force = true
